import React, { useState } from 'react';
import { Layout } from '../Layout/Layout';
import { 
  Search as SearchIcon, 
  Filter, 
  GraduationCap,
  MapPin, 
  Stethoscope,
  Building,
  Users,
  Eye,
  Bookmark,
  ArrowUpDown,
  ChevronUp,
  ChevronDown,
  Square,
  CheckSquare,
  FileText,
  Download,
  ArrowLeft
} from 'lucide-react';

interface GMEProgram {
  id: string;
  programName: string;
  institution: string;
  profession: string;
  specialty: string;
  subspecialty?: string;
  city: string;
  state: string;
  programType: 'Residency' | 'Fellowship' | 'Internship';
  accreditation: string;
  positions: number;
  programDirector: string;
  website?: string;
  description: string;
  established: number;
}

export function GMEProgramSearch() {
  const [searchQuery, setSearchQuery] = useState('');
  const [filters, setFilters] = useState({
    profession: '',
    specialty: '',
    subspecialty: '',
    state: '',
    programType: ''
  });
  const [showFilters, setShowFilters] = useState(false);
  const [isSearching, setIsSearching] = useState(false);
  const [results, setResults] = useState<GMEProgram[]>([]);
  const [sortBy, setSortBy] = useState<'programName' | 'institution' | 'specialty' | 'state'>('programName');
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('asc');
  const [selectedPrograms, setSelectedPrograms] = useState<Set<string>>(new Set());
  const [showBulkActions, setShowBulkActions] = useState(false);
  const [viewMode, setViewMode] = useState<'programs' | 'institutions'>('programs');
  const [selectedInstitution, setSelectedInstitution] = useState<string | null>(null);

  // Mock GME program data
  const mockResults: GMEProgram[] = [
    // Johns Hopkins Hospital - 18 programs
    {
      id: '1',
      programName: 'Internal Medicine Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 52,
      programDirector: 'Dr. Sarah Johnson, MD',
      website: 'https://hopkinsmedicine.org/internal-medicine',
      description: 'Premier internal medicine training with world-class research opportunities and subspecialty rotations.',
      established: 1889
    },
    {
      id: '2',
      programName: 'Surgery Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Surgery',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 48,
      programDirector: 'Dr. Michael Chen, MD',
      website: 'https://hopkinsmedicine.org/surgery',
      description: 'Comprehensive surgical training with emphasis on innovation and minimally invasive techniques.',
      established: 1889
    },
    {
      id: '3',
      programName: 'Emergency Medicine Residency',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Emergency Medicine',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 36,
      programDirector: 'Dr. Emily Rodriguez, MD',
      website: 'https://hopkinsmedicine.org/emergency-medicine',
      description: 'High-acuity emergency medicine training with trauma, pediatric, and critical care focus.',
      established: 1972
    },
    {
      id: '4',
      programName: 'Anesthesiology Residency',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 32,
      programDirector: 'Dr. James Wilson, MD',
      website: 'https://hopkinsmedicine.org/anesthesiology',
      description: 'Advanced anesthesiology training with cardiac, pediatric, and pain management subspecialties.',
      established: 1945
    },
    {
      id: '5',
      programName: 'Neurology Residency',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Neurology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 28,
      programDirector: 'Dr. Lisa Anderson, MD',
      website: 'https://hopkinsmedicine.org/neurology',
      description: 'World-renowned neurology training with cutting-edge research in neurological disorders.',
      established: 1925
    },
    {
      id: '6',
      programName: 'Psychiatry Residency',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Psychiatry',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Robert Kim, MD',
      website: 'https://hopkinsmedicine.org/psychiatry',
      description: 'Comprehensive psychiatry training with research focus on mood disorders and psychopharmacology.',
      established: 1913
    },
    {
      id: '7',
      programName: 'Radiology Residency',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. Maria Garcia, MD',
      website: 'https://hopkinsmedicine.org/radiology',
      description: 'State-of-the-art radiology training with advanced imaging technologies and interventional procedures.',
      established: 1950
    },
    {
      id: '8',
      programName: 'Pathology Residency',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Pathology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. David Lee, MD',
      website: 'https://hopkinsmedicine.org/pathology',
      description: 'Comprehensive pathology training with emphasis on molecular diagnostics and research.',
      established: 1889
    },
    {
      id: '9',
      programName: 'Orthopedic Surgery Residency',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. Jennifer Brown, MD',
      website: 'https://hopkinsmedicine.org/orthopedic-surgery',
      description: 'Premier orthopedic surgery training with sports medicine and joint replacement focus.',
      established: 1920
    },
    {
      id: '10',
      programName: 'Neurosurgery Residency',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Neurosurgery',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 12,
      programDirector: 'Dr. Thomas White, MD',
      website: 'https://hopkinsmedicine.org/neurosurgery',
      id: '5',
      programName: 'Anesthesiology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 32,
      programDirector: 'Dr. Lisa Park, MD',
      website: 'https://hopkinsmedicine.org/anesthesiology',
      description: 'Advanced anesthesiology training with cardiac, pediatric, and pain management subspecialties.',
      established: 1945
    },
    {
      id: '6',
      programName: 'Radiology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Robert Kim, MD',
      website: 'https://hopkinsmedicine.org/radiology',
      description: 'Cutting-edge radiology training with advanced imaging and interventional procedures.',
      established: 1950
    },
    {
      id: '7',
      programName: 'Psychiatry Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Psychiatry',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 28,
      programDirector: 'Dr. Maria Garcia, MD',
      website: 'https://hopkinsmedicine.org/psychiatry',
      description: 'Comprehensive psychiatry training with research opportunities in neuroscience and mental health.',
      established: 1913
    },
    {
      id: '8',
      programName: 'Orthopedic Surgery Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. David Thompson, MD',
      website: 'https://hopkinsmedicine.org/orthopedics',
      description: 'Premier orthopedic surgery training with sports medicine and spine subspecialty tracks.',
      established: 1925
    },
    {
      id: '9',
      programName: 'Neurology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Neurology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Jennifer Lee, MD',
      website: 'https://hopkinsmedicine.org/neurology',
      description: 'World-renowned neurology training with cutting-edge research in neurological disorders.',
      established: 1935
    },
    {
      id: '10',
      programName: 'Obstetrics and Gynecology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Obstetrics and Gynecology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. Amanda White, MD',
      website: 'https://hopkinsmedicine.org/obgyn',
      description: 'Comprehensive OB/GYN training with maternal-fetal medicine and gynecologic oncology.',
      established: 1920
    },
    {
      id: '11',
      programName: 'Pathology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Pathology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Steven Brown, MD',
      website: 'https://hopkinsmedicine.org/pathology',
      description: 'Leading pathology training with anatomic and clinical pathology subspecialties.',
      established: 1889
    },
    {
      id: '12',
      programName: 'Dermatology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Dermatology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 12,
      programDirector: 'Dr. Rachel Davis, MD',
      website: 'https://hopkinsmedicine.org/dermatology',
      description: 'Premier dermatology training with dermatopathology and Mohs surgery opportunities.',
      established: 1960
    },
    {
      id: '13',
      programName: 'Ophthalmology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Ophthalmology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Kevin Martinez, MD',
      website: 'https://hopkinsmedicine.org/ophthalmology',
      description: 'World-class ophthalmology training with retina, cornea, and oculoplastics subspecialties.',
      established: 1925
    },
    {
      id: '14',
      programName: 'Otolaryngology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Otolaryngology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 12,
      programDirector: 'Dr. Patricia Johnson, MD',
      website: 'https://hopkinsmedicine.org/otolaryngology',
      description: 'Comprehensive ENT training with head and neck surgery and rhinology subspecialties.',
      established: 1930
    },
    {
      id: '15',
      programName: 'Urology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Urology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Thomas Anderson, MD',
      website: 'https://hopkinsmedicine.org/urology',
      description: 'Leading urology training with robotic surgery and urologic oncology expertise.',
      established: 1915
    },
    {
      id: '16',
      programName: 'Neurosurgery Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Neurosurgery',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 8,
      programDirector: 'Dr. Michelle Taylor, MD',
      website: 'https://hopkinsmedicine.org/neurosurgery',
      description: 'Premier neurosurgery training with pediatric, vascular, and spine subspecialties.',
      established: 1922
    },
    {
      id: '17',
      programName: 'Plastic Surgery Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Plastic Surgery',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 8,
      programDirector: 'Dr. Christopher Wilson, MD',
      website: 'https://hopkinsmedicine.org/plastic-surgery',
      description: 'Comprehensive plastic surgery training with reconstructive and aesthetic surgery focus.',
      established: 1940
    },
    {
      id: '18',
      programName: 'Radiation Oncology Residency Program',
      institution: 'Johns Hopkins Hospital',
      profession: 'Physician',
      specialty: 'Radiation Oncology',
      city: 'Baltimore',
      state: 'MD',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 12,
      programDirector: 'Dr. Laura Miller, MD',
      website: 'https://hopkinsmedicine.org/radiation-oncology',
      description: 'Advanced radiation oncology training with stereotactic radiosurgery and proton therapy.',
      established: 1955
    },

    // Massachusetts General Hospital - 16 programs (Large Academic Medical Center)
    {
      id: '19',
      programName: 'Internal Medicine Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 48,
      programDirector: 'Dr. Elizabeth Adams, MD',
      website: 'https://mgh.harvard.edu/internal-medicine',
      description: 'Harvard-affiliated internal medicine training with exceptional research opportunities.',
      established: 1821
    },
    {
      id: '20',
      programName: 'Surgery Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Surgery',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 32,
      programDirector: 'Dr. Mark Roberts, MD',
      website: 'https://mgh.harvard.edu/surgery',
      description: 'Historic surgical training program with innovation in minimally invasive techniques.',
      established: 1821
    },
    {
      id: '21',
      programName: 'Emergency Medicine Residency',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Emergency Medicine',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 40,
      programDirector: 'Dr. Susan Clark, MD',
      website: 'https://mgh.harvard.edu/emergency-medicine',
      description: 'Leading emergency medicine training with disaster medicine and toxicology expertise.',
      established: 1972
    },
    {
      id: '22',
      programName: 'Anesthesiology Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 36,
      programDirector: 'Dr. Daniel Lewis, MD',
      website: 'https://mgh.harvard.edu/anesthesiology',
      description: 'Premier anesthesiology training with cardiac, neuroanesthesia, and pain management.',
      established: 1846
    },
    {
      id: '23',
      programName: 'Radiology Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 28,
      programDirector: 'Dr. Nancy Walker, MD',
      website: 'https://mgh.harvard.edu/radiology',
      description: 'Advanced radiology training with AI integration and interventional procedures.',
      established: 1896
    },
    {
      id: '24',
      programName: 'Psychiatry Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Psychiatry',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 32,
      programDirector: 'Dr. Paul Young, MD',
      website: 'https://mgh.harvard.edu/psychiatry',
      description: 'Harvard-affiliated psychiatry training with neuroscience research opportunities.',
      established: 1934
    },
    {
      id: '25',
      programName: 'Pediatrics Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Pediatrics',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 36,
      programDirector: 'Dr. Karen Hall, MD',
      website: 'https://mgh.harvard.edu/pediatrics',
      description: 'Comprehensive pediatric training with Boston Children\'s Hospital rotations.',
      established: 1888
    },
    {
      id: '26',
      programName: 'Orthopedic Surgery Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Richard Green, MD',
      website: 'https://mgh.harvard.edu/orthopedics',
      description: 'Leading orthopedic surgery training with sports medicine and joint replacement focus.',
      established: 1900
    },
    {
      id: '27',
      programName: 'Neurology Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Neurology',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 28,
      programDirector: 'Dr. Helen Baker, MD',
      website: 'https://mgh.harvard.edu/neurology',
      description: 'World-class neurology training with stroke, epilepsy, and movement disorders expertise.',
      established: 1925
    },
    {
      id: '28',
      programName: 'Obstetrics and Gynecology Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Obstetrics and Gynecology',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Lisa Turner, MD',
      website: 'https://mgh.harvard.edu/obgyn',
      description: 'Comprehensive OB/GYN training with high-risk obstetrics and minimally invasive surgery.',
      established: 1875
    },
    {
      id: '29',
      programName: 'Dermatology Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Dermatology',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Andrew Phillips, MD',
      website: 'https://mgh.harvard.edu/dermatology',
      description: 'Premier dermatology training with dermatopathology and cosmetic dermatology.',
      established: 1950
    },
    {
      id: '30',
      programName: 'Ophthalmology Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Ophthalmology',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. Margaret Evans, MD',
      website: 'https://mgh.harvard.edu/ophthalmology',
      description: 'Leading ophthalmology training with retina, glaucoma, and cornea subspecialties.',
      established: 1930
    },
    {
      id: '31',
      programName: 'Pathology Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Pathology',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. Joseph Collins, MD',
      website: 'https://mgh.harvard.edu/pathology',
      description: 'Comprehensive pathology training with molecular diagnostics and digital pathology.',
      established: 1896
    },
    {
      id: '32',
      programName: 'Neurosurgery Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Neurosurgery',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 12,
      programDirector: 'Dr. Catherine Stewart, MD',
      website: 'https://mgh.harvard.edu/neurosurgery',
      description: 'Premier neurosurgery training with brain tumor, vascular, and functional neurosurgery.',
      established: 1920
    },
    {
      id: '33',
      programName: 'Urology Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Urology',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. Brian Morris, MD',
      website: 'https://mgh.harvard.edu/urology',
      description: 'Advanced urology training with robotic surgery and urologic oncology expertise.',
      established: 1910
    },
    {
      id: '34',
      programName: 'Otolaryngology Residency Program',
      institution: 'Massachusetts General Hospital',
      profession: 'Physician',
      specialty: 'Otolaryngology',
      city: 'Boston',
      state: 'MA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Sandra Rogers, MD',
      website: 'https://mgh.harvard.edu/otolaryngology',
      description: 'Comprehensive ENT training with head and neck oncology and facial plastic surgery.',
      established: 1925
    },

    // UCLA Medical Center - 14 programs (Large Academic Medical Center)
    {
      id: '35',
      programName: 'Internal Medicine Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 45,
      programDirector: 'Dr. Maria Gonzalez, MD',
      website: 'https://ucla.edu/internal-medicine',
      description: 'Comprehensive internal medicine training with emphasis on primary care and subspecialty rotations.',
      established: 1965
    },
    {
      id: '36',
      programName: 'Surgery Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Surgery',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 30,
      programDirector: 'Dr. James Kim, MD',
      website: 'https://ucla.edu/surgery',
      description: 'Advanced surgical training with transplant surgery and minimally invasive techniques.',
      established: 1965
    },
    {
      id: '37',
      programName: 'Emergency Medicine Residency',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Emergency Medicine',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 38,
      programDirector: 'Dr. Robert Chen, MD',
      website: 'https://ucla.edu/emergency-medicine',
      description: 'High-volume emergency medicine training with trauma and critical care emphasis.',
      established: 1975
    },
    {
      id: '38',
      programName: 'Pediatrics Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Pediatrics',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 40,
      programDirector: 'Dr. Jennifer Wang, MD',
      website: 'https://ucla.edu/pediatrics',
      description: 'Comprehensive pediatric training with UCLA Mattel Children\'s Hospital rotations.',
      established: 1968
    },
    {
      id: '39',
      programName: 'Anesthesiology Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 34,
      programDirector: 'Dr. Michael Davis, MD',
      website: 'https://ucla.edu/anesthesiology',
      description: 'Advanced anesthesiology training with cardiac, pediatric, and neuroanesthesia subspecialties.',
      established: 1970
    },
    {
      id: '40',
      programName: 'Radiology Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 26,
      programDirector: 'Dr. Lisa Thompson, MD',
      website: 'https://ucla.edu/radiology',
      description: 'Cutting-edge radiology training with advanced imaging and interventional radiology.',
      established: 1972
    },
    {
      id: '41',
      programName: 'Psychiatry Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Psychiatry',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 30,
      programDirector: 'Dr. Sarah Martinez, MD',
      website: 'https://ucla.edu/psychiatry',
      description: 'Comprehensive psychiatry training with neuroscience research and community mental health.',
      established: 1968
    },
    {
      id: '42',
      programName: 'Orthopedic Surgery Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 22,
      programDirector: 'Dr. David Wilson, MD',
      website: 'https://ucla.edu/orthopedics',
      description: 'Premier orthopedic surgery training with sports medicine and spine surgery expertise.',
      established: 1975
    },
    {
      id: '43',
      programName: 'Neurology Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Neurology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 26,
      programDirector: 'Dr. Patricia Lee, MD',
      website: 'https://ucla.edu/neurology',
      description: 'World-class neurology training with stroke, epilepsy, and movement disorders programs.',
      established: 1978
    },
    {
      id: '44',
      programName: 'Obstetrics and Gynecology Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Obstetrics and Gynecology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 22,
      programDirector: 'Dr. Karen Brown, MD',
      website: 'https://ucla.edu/obgyn',
      description: 'Comprehensive OB/GYN training with maternal-fetal medicine and reproductive endocrinology.',
      established: 1970
    },
    {
      id: '45',
      programName: 'Dermatology Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Dermatology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 14,
      programDirector: 'Dr. Steven Garcia, MD',
      website: 'https://ucla.edu/dermatology',
      description: 'Premier dermatology training with dermatopathology and cosmetic dermatology focus.',
      established: 1980
    },
    {
      id: '46',
      programName: 'Ophthalmology Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Ophthalmology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 18,
      programDirector: 'Dr. Michelle Taylor, MD',
      website: 'https://ucla.edu/ophthalmology',
      description: 'Leading ophthalmology training with retina, cornea, and oculoplastics subspecialties.',
      established: 1975
    },
    {
      id: '47',
      programName: 'Neurosurgery Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Neurosurgery',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 10,
      programDirector: 'Dr. Christopher Anderson, MD',
      website: 'https://ucla.edu/neurosurgery',
      description: 'Premier neurosurgery training with pediatric, vascular, and functional neurosurgery.',
      established: 1978
    },
    {
      id: '48',
      programName: 'Urology Residency Program',
      institution: 'UCLA Medical Center',
      profession: 'Physician',
      specialty: 'Urology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 18,
      programDirector: 'Dr. Laura Miller, MD',
      website: 'https://ucla.edu/urology',
      description: 'Advanced urology training with robotic surgery and urologic oncology expertise.',
      established: 1972
    },

    // Mayo Clinic Rochester - 12 programs (Large Academic Medical Center)
    {
      id: '49',
      programName: 'Internal Medicine Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 42,
      programDirector: 'Dr. Thomas Johnson, MD',
      website: 'https://mayo.edu/internal-medicine',
      description: 'World-renowned internal medicine training with integrated practice model and research.',
      established: 1915
    },
    {
      id: '50',
      programName: 'Surgery Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Surgery',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 26,
      programDirector: 'Dr. Elizabeth Smith, MD',
      website: 'https://mayo.edu/surgery',
      description: 'Comprehensive surgical training with transplant surgery and minimally invasive techniques.',
      established: 1915
    },
    {
      id: '51',
      programName: 'Anesthesiology Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 30,
      programDirector: 'Dr. Mark Williams, MD',
      website: 'https://mayo.edu/anesthesiology',
      description: 'Premier anesthesiology training with cardiac, neuroanesthesia, and pain management.',
      established: 1920
    },
    {
      id: '52',
      programName: 'Radiology Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Jennifer Davis, MD',
      website: 'https://mayo.edu/radiology',
      description: 'Advanced radiology training with AI integration and interventional procedures.',
      established: 1925
    },
    {
      id: '53',
      programName: 'Psychiatry Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Psychiatry',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 26,
      programDirector: 'Dr. Robert Wilson, MD',
      website: 'https://mayo.edu/psychiatry',
      description: 'Comprehensive psychiatry training with integrated medical and psychiatric care.',
      established: 1930
    },
    {
      id: '54',
      programName: 'Orthopedic Surgery Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. Susan Brown, MD',
      website: 'https://mayo.edu/orthopedics',
      description: 'Leading orthopedic surgery training with sports medicine and joint replacement expertise.',
      established: 1935
    },
    {
      id: '55',
      programName: 'Neurology Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Neurology',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 22,
      programDirector: 'Dr. Paul Garcia, MD',
      website: 'https://mayo.edu/neurology',
      description: 'World-class neurology training with movement disorders and epilepsy expertise.',
      established: 1928
    },
    {
      id: '56',
      programName: 'Dermatology Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Dermatology',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 12,
      programDirector: 'Dr. Lisa Martinez, MD',
      website: 'https://mayo.edu/dermatology',
      description: 'Premier dermatology training with dermatopathology and Mohs surgery focus.',
      established: 1955
    },
    {
      id: '57',
      programName: 'Ophthalmology Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Ophthalmology',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Kevin Lee, MD',
      website: 'https://mayo.edu/ophthalmology',
      description: 'Leading ophthalmology training with retina, glaucoma, and oculoplastics subspecialties.',
      established: 1940
    },
    {
      id: '58',
      programName: 'Neurosurgery Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Neurosurgery',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 8,
      programDirector: 'Dr. Amanda Clark, MD',
      website: 'https://mayo.edu/neurosurgery',
      description: 'Premier neurosurgery training with brain tumor, spine, and vascular neurosurgery.',
      established: 1932
    },
    {
      id: '59',
      programName: 'Urology Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Urology',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Daniel Turner, MD',
      website: 'https://mayo.edu/urology',
      description: 'Advanced urology training with robotic surgery and urologic oncology expertise.',
      established: 1925
    },
    {
      id: '60',
      programName: 'Pathology Residency Program',
      institution: 'Mayo Clinic Rochester',
      profession: 'Physician',
      specialty: 'Pathology',
      city: 'Rochester',
      state: 'MN',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 18,
      programDirector: 'Dr. Michelle Hall, MD',
      website: 'https://mayo.edu/pathology',
      description: 'Comprehensive pathology training with molecular diagnostics and digital pathology.',
      established: 1920
    },

    // Cleveland Clinic - 11 programs (Large Academic Medical Center)
    {
      id: '61',
      programName: 'Internal Medicine Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 40,
      programDirector: 'Dr. Richard Baker, MD',
      website: 'https://clevelandclinic.org/internal-medicine',
      description: 'Comprehensive internal medicine training with emphasis on cardiovascular medicine.',
      established: 1921
    },
    {
      id: '62',
      programName: 'Surgery Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Surgery',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 28,
      programDirector: 'Dr. Helen Young, MD',
      website: 'https://clevelandclinic.org/surgery',
      description: 'Advanced surgical training with transplant surgery and minimally invasive techniques.',
      established: 1921
    },
    {
      id: '63',
      programName: 'Anesthesiology Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 32,
      programDirector: 'Dr. Joseph Phillips, MD',
      website: 'https://clevelandclinic.org/anesthesiology',
      description: 'Premier anesthesiology training with cardiac, neuroanesthesia, and pain management.',
      established: 1925
    },
    {
      id: '64',
      programName: 'Emergency Medicine Residency',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Emergency Medicine',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 36,
      programDirector: 'Dr. Catherine Evans, MD',
      website: 'https://clevelandclinic.org/emergency-medicine',
      description: 'High-volume emergency medicine training with trauma and critical care emphasis.',
      established: 1980
    },
    {
      id: '65',
      programName: 'Radiology Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 22,
      programDirector: 'Dr. Brian Stewart, MD',
      website: 'https://clevelandclinic.org/radiology',
      description: 'Advanced radiology training with cardiovascular imaging and interventional procedures.',
      established: 1930
    },
    {
      id: '66',
      programName: 'Orthopedic Surgery Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 18,
      programDirector: 'Dr. Sandra Morris, MD',
      website: 'https://clevelandclinic.org/orthopedics',
      description: 'Leading orthopedic surgery training with sports medicine and joint replacement expertise.',
      established: 1935
    },
    {
      id: '67',
      programName: 'Neurology Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Neurology',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. Margaret Rogers, MD',
      website: 'https://clevelandclinic.org/neurology',
      description: 'World-class neurology training with stroke, epilepsy, and movement disorders programs.',
      established: 1940
    },
    {
      id: '68',
      programName: 'Neurosurgery Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Neurosurgery',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 10,
      programDirector: 'Dr. Christopher Collins, MD',
      website: 'https://clevelandclinic.org/neurosurgery',
      description: 'Premier neurosurgery training with brain tumor, spine, and vascular neurosurgery.',
      established: 1945
    },
    {
      id: '69',
      programName: 'Urology Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Urology',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 14,
      programDirector: 'Dr. Laura Walker, MD',
      website: 'https://clevelandclinic.org/urology',
      description: 'Advanced urology training with robotic surgery and urologic oncology expertise.',
      established: 1930
    },
    {
      id: '70',
      programName: 'Dermatology Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Dermatology',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 10,
      programDirector: 'Dr. Andrew Lewis, MD',
      website: 'https://clevelandclinic.org/dermatology',
      description: 'Premier dermatology training with dermatopathology and cosmetic dermatology focus.',
      established: 1960
    },
    {
      id: '71',
      programName: 'Pathology Residency Program',
      institution: 'Cleveland Clinic',
      profession: 'Physician',
      specialty: 'Pathology',
      city: 'Cleveland',
      state: 'OH',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Nancy Green, MD',
      website: 'https://clevelandclinic.org/pathology',
      description: 'Comprehensive pathology training with molecular diagnostics and cardiovascular pathology.',
      established: 1925
    },

    // Stanford University Medical Center - 10 programs (Large Academic Medical Center)
    {
      id: '72',
      programName: 'Internal Medicine Residency Program',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 38,
      programDirector: 'Dr. Paul Turner, MD',
      website: 'https://stanford.edu/internal-medicine',
      description: 'Premier internal medicine training with emphasis on innovation and technology integration.',
      established: 1959
    },
    {
      id: '73',
      programName: 'Surgery Residency Program',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Surgery',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 26,
      programDirector: 'Dr. Karen Hall, MD',
      website: 'https://stanford.edu/surgery',
      description: 'Advanced surgical training with transplant surgery and robotic surgery expertise.',
      established: 1959
    },
    {
      id: '74',
      programName: 'Anesthesiology Residency Program',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 28,
      programDirector: 'Dr. Richard Adams, MD',
      website: 'https://stanford.edu/anesthesiology',
      description: 'Premier anesthesiology training with cardiac, pediatric, and neuroanesthesia subspecialties.',
      established: 1965
    },
    {
      id: '75',
      programName: 'Emergency Medicine Residency',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Emergency Medicine',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 32,
      programDirector: 'Dr. Elizabeth Roberts, MD',
      website: 'https://stanford.edu/emergency-medicine',
      description: 'High-volume emergency medicine training with trauma and disaster medicine focus.',
      established: 1978
    },
    {
      id: '76',
      programName: 'Radiology Residency Program',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 20,
      programDirector: 'Dr. Mark Clark, MD',
      website: 'https://stanford.edu/radiology',
      description: 'Advanced radiology training with AI integration and interventional radiology.',
      established: 1970
    },
    {
      id: '77',
      programName: 'Neurology Residency Program',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Neurology',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 18,
      programDirector: 'Dr. Susan Lewis, MD',
      website: 'https://stanford.edu/neurology',
      description: 'World-class neurology training with movement disorders and epilepsy expertise.',
      established: 1975
    },
    {
      id: '78',
      programName: 'Neurosurgery Residency Program',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Neurosurgery',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 8,
      programDirector: 'Dr. Daniel Young, MD',
      website: 'https://stanford.edu/neurosurgery',
      description: 'Premier neurosurgery training with pediatric, functional, and vascular neurosurgery.',
      established: 1970
    },
    {
      id: '79',
      programName: 'Orthopedic Surgery Residency Program',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Lisa Baker, MD',
      website: 'https://stanford.edu/orthopedics',
      description: 'Leading orthopedic surgery training with sports medicine and joint replacement expertise.',
      established: 1972
    },
    {
      id: '80',
      programName: 'Dermatology Residency Program',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Dermatology',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 12,
      programDirector: 'Dr. Helen Phillips, MD',
      website: 'https://stanford.edu/dermatology',
      description: 'Premier dermatology training with dermatopathology and cosmetic dermatology focus.',
      established: 1980
    },
    {
      id: '81',
      programName: 'Family Medicine Residency',
      institution: 'Stanford University Medical Center',
      profession: 'Physician',
      specialty: 'Family Medicine',
      city: 'Stanford',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. James Wilson, MD',
      website: 'https://stanford.edu/family-medicine',
      description: 'Community-based family medicine training with rural and underserved population focus.',
      established: 1972
    },

    // UCSF Medical Center - 9 programs (Large Academic Medical Center)
    {
      id: '82',
      programName: 'Internal Medicine Residency Program',
      institution: 'UCSF Medical Center',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'San Francisco',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 44,
      programDirector: 'Dr. Margaret Evans, MD',
      website: 'https://ucsf.edu/internal-medicine',
      description: 'Premier internal medicine training with emphasis on primary care and global health.',
      established: 1958
    },
    {
      id: '83',
      programName: 'Surgery Residency Program',
      institution: 'UCSF Medical Center',
      profession: 'Physician',
      specialty: 'Surgery',
      city: 'San Francisco',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 30,
      programDirector: 'Dr. Joseph Stewart, MD',
      website: 'https://ucsf.edu/surgery',
      description: 'Advanced surgical training with transplant surgery and minimally invasive techniques.',
      established: 1958
    },
    {
      id: '84',
      programName: 'Emergency Medicine Residency',
      institution: 'UCSF Medical Center',
      profession: 'Physician',
      specialty: 'Emergency Medicine',
      city: 'San Francisco',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 32,
      programDirector: 'Dr. Michael Chen, MD',
      website: 'https://ucsf.edu/emergency-medicine',
      description: 'High-volume emergency medicine training with trauma, pediatric, and critical care rotations.',
      established: 1978
    },
    {
      id: '85',
      programName: 'Anesthesiology Residency Program',
      institution: 'UCSF Medical Center',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'San Francisco',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 30,
      programDirector: 'Dr. Catherine Morris, MD',
      website: 'https://ucsf.edu/anesthesiology',
      description: 'Premier anesthesiology training with cardiac, pediatric, and neuroanesthesia subspecialties.',
      established: 1965
    },
    {
      id: '86',
      programName: 'Radiology Residency Program',
      institution: 'UCSF Medical Center',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'San Francisco',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Brian Rogers, MD',
      website: 'https://ucsf.edu/radiology',
      description: 'Advanced radiology training with AI integration and interventional radiology.',
      established: 1970
    },
    {
      id: '87',
      programName: 'Neurology Residency Program',
      institution: 'UCSF Medical Center',
      profession: 'Physician',
      specialty: 'Neurology',
      city: 'San Francisco',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 22,
      programDirector: 'Dr. Sandra Collins, MD',
      website: 'https://ucsf.edu/neurology',
      description: 'World-class neurology training with movement disorders and epilepsy expertise.',
      established: 1975
    },
    {
      id: '88',
      programName: 'Neurosurgery Residency Program',
      institution: 'UCSF Medical Center',
      profession: 'Physician',
      specialty: 'Neurosurgery',
      city: 'San Francisco',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 10,
      programDirector: 'Dr. Laura Walker, MD',
      website: 'https://ucsf.edu/neurosurgery',
      description: 'Premier neurosurgery training with pediatric, functional, and vascular neurosurgery.',
      established: 1970
    },
    {
      id: '89',
      programName: 'Orthopedic Surgery Residency Program',
      institution: 'UCSF Medical Center',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'San Francisco',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 18,
      programDirector: 'Dr. Andrew Lewis, MD',
      website: 'https://ucsf.edu/orthopedics',
      description: 'Leading orthopedic surgery training with sports medicine and joint replacement expertise.',
      established: 1972
    },
    {
      id: '90',
      programName: 'Dermatology Residency Program',
      institution: 'UCSF Medical Center',
      profession: 'Physician',
      specialty: 'Dermatology',
      city: 'San Francisco',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 14,
      programDirector: 'Dr. Nancy Green, MD',
      website: 'https://ucsf.edu/dermatology',
      description: 'Premier dermatology training with dermatopathology and cosmetic dermatology focus.',
      established: 1980
    },

    // Cedars-Sinai Medical Center - 8 programs (Medium Academic Medical Center)
    {
      id: '91',
      programName: 'Internal Medicine Residency Program',
      institution: 'Cedars-Sinai Medical Center',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 36,
      programDirector: 'Dr. Paul Turner, MD',
      website: 'https://cedars-sinai.edu/internal-medicine',
      description: 'Comprehensive internal medicine training with emphasis on cardiovascular medicine.',
      established: 1961
    },
    {
      id: '92',
      programName: 'Surgery Residency Program',
      institution: 'Cedars-Sinai Medical Center',
      profession: 'Physician',
      specialty: 'Surgery',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Karen Hall, MD',
      website: 'https://cedars-sinai.edu/surgery',
      description: 'Advanced surgical training with transplant surgery and minimally invasive techniques.',
      established: 1961
    },
    {
      id: '93',
      programName: 'Cardiology Fellowship Program',
      institution: 'Cedars-Sinai Medical Center',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      subspecialty: 'Cardiology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Fellowship',
      accreditation: 'ACGME',
      positions: 12,
      programDirector: 'Dr. Emily Rodriguez, MD',
      website: 'https://cedars-sinai.edu/cardiology',
      description: 'Advanced cardiology fellowship with interventional, electrophysiology, and heart failure tracks.',
      established: 1985
    },
    {
      id: '94',
      programName: 'Emergency Medicine Residency',
      institution: 'Cedars-Sinai Medical Center',
      profession: 'Physician',
      specialty: 'Emergency Medicine',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 28,
      programDirector: 'Dr. Richard Adams, MD',
      website: 'https://cedars-sinai.edu/emergency-medicine',
      description: 'High-volume emergency medicine training with trauma and critical care emphasis.',
      established: 1982
    },
    {
      id: '95',
      programName: 'Anesthesiology Residency Program',
      institution: 'Cedars-Sinai Medical Center',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 26,
      programDirector: 'Dr. Elizabeth Roberts, MD',
      website: 'https://cedars-sinai.edu/anesthesiology',
      description: 'Premier anesthesiology training with cardiac and neuroanesthesia subspecialties.',
      established: 1970
    },
    {
      id: '96',
      programName: 'Radiology Residency Program',
      institution: 'Cedars-Sinai Medical Center',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 18,
      programDirector: 'Dr. Mark Clark, MD',
      website: 'https://cedars-sinai.edu/radiology',
      description: 'Advanced radiology training with cardiovascular imaging and interventional procedures.',
      established: 1975
    },
    {
      id: '97',
      programName: 'Orthopedic Surgery Residency Program',
      institution: 'Cedars-Sinai Medical Center',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Susan Lewis, MD',
      website: 'https://cedars-sinai.edu/orthopedics',
      description: 'Leading orthopedic surgery training with sports medicine and joint replacement expertise.',
      established: 1980
    },
    {
      id: '98',
      programName: 'Neurology Residency Program',
      institution: 'Cedars-Sinai Medical Center',
      profession: 'Physician',
      specialty: 'Neurology',
      city: 'Los Angeles',
      state: 'CA',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 14,
      programDirector: 'Dr. Daniel Young, MD',
      website: 'https://cedars-sinai.edu/neurology',
      description: 'World-class neurology training with movement disorders and stroke expertise.',
      established: 1985
    },

    // Mount Sinai Hospital - 6 programs (Medium Academic Medical Center)
    {
      id: '99',
      programName: 'Internal Medicine Residency Program',
      institution: 'Mount Sinai Hospital',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'New York',
      state: 'NY',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 34,
      programDirector: 'Dr. Lisa Baker, MD',
      website: 'https://mountsinai.org/internal-medicine',
      description: 'Comprehensive internal medicine training with emphasis on urban healthcare.',
      established: 1968
    },
    {
      id: '100',
      programName: 'Surgery Residency Program',
      institution: 'Mount Sinai Hospital',
      profession: 'Physician',
      specialty: 'Surgery',
      city: 'New York',
      state: 'NY',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 22,
      programDirector: 'Dr. Helen Phillips, MD',
      website: 'https://mountsinai.org/surgery',
      description: 'Advanced surgical training with transplant surgery and minimally invasive techniques.',
      established: 1968
    },
    {
      id: '101',
      programName: 'Emergency Medicine Residency',
      institution: 'Mount Sinai Hospital',
      profession: 'Physician',
      specialty: 'Emergency Medicine',
      city: 'New York',
      state: 'NY',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 30,
      programDirector: 'Dr. James Evans, MD',
      website: 'https://mountsinai.org/emergency-medicine',
      description: 'High-volume emergency medicine training with trauma and urban emergency care.',
      established: 1985
    },
    {
      id: '102',
      programName: 'Anesthesiology Residency Program',
      institution: 'Mount Sinai Hospital',
      profession: 'Physician',
      specialty: 'Anesthesiology',
      city: 'New York',
      state: 'NY',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Margaret Stewart, MD',
      website: 'https://mountsinai.org/anesthesiology',
      description: 'Premier anesthesiology training with cardiac and neuroanesthesia subspecialties.',
      established: 1975
    },
    {
      id: '103',
      programName: 'Radiology Residency Program',
      institution: 'Mount Sinai Hospital',
      profession: 'Physician',
      specialty: 'Radiology',
      city: 'New York',
      state: 'NY',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 16,
      programDirector: 'Dr. Joseph Morris, MD',
      website: 'https://mountsinai.org/radiology',
      description: 'Advanced radiology training with interventional radiology and advanced imaging.',
      established: 1980
    },
    {
      id: '104',
      programName: 'Orthopedic Surgery Residency Program',
      institution: 'Mount Sinai Hospital',
      profession: 'Physician',
      specialty: 'Orthopedic Surgery',
      city: 'New York',
      state: 'NY',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 14,
      programDirector: 'Dr. Catherine Rogers, MD',
      website: 'https://mountsinai.org/orthopedics',
      description: 'Leading orthopedic surgery training with sports medicine and joint replacement expertise.',
      established: 1985
    },

    // Community Medical Center - 5 programs (Community Hospital)
    {
      id: '105',
      programName: 'Family Medicine Residency',
      institution: 'Community Medical Center',
      profession: 'Physician',
      specialty: 'Family Medicine',
      city: 'Phoenix',
      state: 'AZ',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 18,
      programDirector: 'Dr. Brian Collins, MD',
      website: 'https://communitymedical.org/family-medicine',
      description: 'Community-based family medicine training with rural and underserved population focus.',
      established: 1985
    },
    {
      id: '106',
      programName: 'Internal Medicine Residency Program',
      institution: 'Community Medical Center',
      profession: 'Physician',
      specialty: 'Internal Medicine',
      city: 'Phoenix',
      state: 'AZ',
      programType: 'Residency',
      accreditation: 'ACGME',
      positions: 24,
      programDirector: 'Dr. Sandra Walker, MD',
      website: 
    }
  ]
}