/*
  # Populate GME Business Review Data Table

  1. Mock Data Insertion
    - Insert comprehensive GME program data covering various specialties
    - Include residency and fellowship programs
    - Populate salary, benefits, rotations, and statistics data
    - Cover multiple states and institution types

  2. Data Coverage
    - 25+ programs across different specialties
    - Mix of academic medical centers and community hospitals
    - Realistic salary ranges and program details
    - Comprehensive benefits and rotation schedules
*/

-- Insert mock GME program data
INSERT INTO gme_business_review_data (
  program_name,
  institution,
  specialty,
  program_type,
  city,
  state,
  positions,
  program_director,
  website,
  application_deadline,
  match_date,
  established_year,
  accreditation,
  duration_years,
  salary_pgy1,
  salary_pgy2,
  salary_pgy3,
  benefits,
  rotations,
  requirements,
  statistics,
  fellowship_placements,
  contact_email,
  contact_phone,
  description,
  source_file,
  imported_by,
  imported_at
) VALUES 
-- Internal Medicine Programs
(
  'Internal Medicine Residency Program',
  'UCLA Medical Center',
  'Internal Medicine',
  'Residency',
  'Los Angeles',
  'CA',
  45,
  'Dr. Sarah Johnson, MD',
  'https://medicine.ucla.edu/internal-medicine',
  'October 15, 2024',
  'March 15, 2025',
  1965,
  'ACGME',
  3,
  65000,
  67000,
  69000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,500)', 'Vacation (4 weeks)', 'Sick leave', 'Parental leave'],
  ARRAY['Internal Medicine Wards', 'ICU/CCU', 'Emergency Medicine', 'Ambulatory Medicine', 'Cardiology', 'Gastroenterology', 'Pulmonology', 'Endocrinology', 'Nephrology', 'Rheumatology', 'Infectious Disease', 'Electives'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'ECFMG certification (IMG)', 'Strong clinical performance', 'Research experience preferred'],
  '{"applications": 2800, "interviews": 180, "match_rate": "95%", "board_pass_rate": "98%", "chief_residents": 6}'::jsonb,
  ARRAY['Cardiology (8)', 'Gastroenterology (5)', 'Pulmonology (4)', 'Endocrinology (3)', 'Nephrology (2)', 'Hospitalist (12)'],
  'internal.medicine@ucla.edu',
  '(310) 825-6301',
  'Comprehensive training in internal medicine with emphasis on primary care, subspecialty rotations, and research opportunities.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),
(
  'Internal Medicine Residency Program',
  'Johns Hopkins Hospital',
  'Internal Medicine',
  'Residency',
  'Baltimore',
  'MD',
  52,
  'Dr. Michael Chen, MD',
  'https://hopkinsmedicine.org/internal-medicine',
  'October 15, 2024',
  'March 15, 2025',
  1958,
  'ACGME',
  3,
  68000,
  70000,
  72000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($3,000)', 'Vacation (4 weeks)', 'Sick leave', 'Parental leave', 'Housing assistance'],
  ARRAY['Internal Medicine Wards', 'ICU/CCU', 'Emergency Medicine', 'Ambulatory Medicine', 'Cardiology', 'Gastroenterology', 'Pulmonology', 'Endocrinology', 'Nephrology', 'Oncology', 'Research'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'ECFMG certification (IMG)', 'Strong clinical performance', 'Research experience required'],
  '{"applications": 3200, "interviews": 200, "match_rate": "97%", "board_pass_rate": "99%", "chief_residents": 8}'::jsonb,
  ARRAY['Cardiology (10)', 'Gastroenterology (6)', 'Pulmonology (5)', 'Endocrinology (4)', 'Nephrology (3)', 'Oncology (7)'],
  'internal.medicine@jhmi.edu',
  '(410) 955-5000',
  'Premier internal medicine training with world-class faculty and cutting-edge research opportunities.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Emergency Medicine Programs
(
  'Emergency Medicine Residency Program',
  'Massachusetts General Hospital',
  'Emergency Medicine',
  'Residency',
  'Boston',
  'MA',
  36,
  'Dr. Emily Rodriguez, MD',
  'https://mgh.harvard.edu/emergency-medicine',
  'October 15, 2024',
  'March 15, 2025',
  1972,
  'ACGME',
  4,
  66000,
  68000,
  70000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,800)', 'Vacation (4 weeks)', 'Sick leave', 'Parental leave'],
  ARRAY['Emergency Department', 'Trauma', 'ICU', 'Pediatric Emergency', 'Toxicology', 'EMS', 'Ultrasound', 'Research', 'Electives'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Strong emergency medicine interest', 'Clinical experience in emergency settings'],
  '{"applications": 2400, "interviews": 150, "match_rate": "93%", "board_pass_rate": "96%", "chief_residents": 4}'::jsonb,
  ARRAY['Emergency Medicine Faculty (15)', 'Critical Care (3)', 'Toxicology (2)', 'EMS (4)'],
  'emergency@mgh.harvard.edu',
  '(617) 726-2000',
  'Leading emergency medicine training program with emphasis on trauma, critical care, and research.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Family Medicine Programs
(
  'Family Medicine Residency Program',
  'University of Texas Southwestern',
  'Family Medicine',
  'Residency',
  'Dallas',
  'TX',
  24,
  'Dr. David Wilson, MD',
  'https://utsouthwestern.edu/family-medicine',
  'October 15, 2024',
  'March 15, 2025',
  1975,
  'ACGME',
  3,
  58000,
  60000,
  62000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,000)', 'Vacation (4 weeks)', 'Sick leave'],
  ARRAY['Family Medicine Clinic', 'Internal Medicine', 'Pediatrics', 'Obstetrics', 'Surgery', 'Emergency Medicine', 'Psychiatry', 'Community Health'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Interest in primary care', 'Community service experience'],
  '{"applications": 1800, "interviews": 120, "match_rate": "90%", "board_pass_rate": "94%", "chief_residents": 3}'::jsonb,
  ARRAY['Family Medicine Faculty (18)', 'Sports Medicine (2)', 'Geriatrics (1)'],
  'family.medicine@utsouthwestern.edu',
  '(214) 648-3111',
  'Comprehensive family medicine training with strong community health focus and rural medicine opportunities.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Pediatrics Programs
(
  'Pediatrics Residency Program',
  'Boston Children''s Hospital',
  'Pediatrics',
  'Residency',
  'Boston',
  'MA',
  42,
  'Dr. Lisa Thompson, MD',
  'https://childrenshospital.org/pediatrics',
  'October 15, 2024',
  'March 15, 2025',
  1960,
  'ACGME',
  3,
  64000,
  66000,
  68000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,500)', 'Vacation (4 weeks)', 'Sick leave', 'Parental leave', 'Childcare assistance'],
  ARRAY['General Pediatrics', 'NICU', 'PICU', 'Pediatric Emergency', 'Adolescent Medicine', 'Pediatric Surgery', 'Cardiology', 'Oncology', 'Neurology', 'Electives'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Strong pediatric interest', 'Experience with children'],
  '{"applications": 2200, "interviews": 160, "match_rate": "92%", "board_pass_rate": "97%", "chief_residents": 5}'::jsonb,
  ARRAY['Pediatric Cardiology (3)', 'Pediatric Oncology (4)', 'Pediatric Surgery (2)', 'NICU (6)', 'General Pediatrics (15)'],
  'pediatrics@childrens.harvard.edu',
  '(617) 355-6000',
  'World-renowned pediatric training with subspecialty excellence and research opportunities.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Surgery Programs
(
  'General Surgery Residency Program',
  'Mayo Clinic',
  'Surgery',
  'Residency',
  'Rochester',
  'MN',
  18,
  'Dr. Robert Martinez, MD',
  'https://mayoclinic.org/surgery',
  'October 15, 2024',
  'March 15, 2025',
  1963,
  'ACGME',
  5,
  67000,
  69000,
  71000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($3,500)', 'Vacation (4 weeks)', 'Sick leave', 'Parental leave'],
  ARRAY['General Surgery', 'Trauma Surgery', 'Vascular Surgery', 'Cardiothoracic Surgery', 'Surgical ICU', 'Emergency Surgery', 'Transplant Surgery', 'Research'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Strong surgical interest', 'Research experience', 'Physical stamina'],
  '{"applications": 1500, "interviews": 90, "match_rate": "88%", "board_pass_rate": "95%", "chief_residents": 2}'::jsonb,
  ARRAY['Cardiothoracic Surgery (2)', 'Vascular Surgery (3)', 'Trauma Surgery (2)', 'Transplant Surgery (1)', 'Surgical Oncology (2)'],
  'surgery@mayo.edu',
  '(507) 284-2511',
  'Comprehensive surgical training with emphasis on minimally invasive techniques and research.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Psychiatry Programs
(
  'Psychiatry Residency Program',
  'Stanford University Medical Center',
  'Psychiatry',
  'Residency',
  'Stanford',
  'CA',
  28,
  'Dr. Jennifer Lee, MD',
  'https://med.stanford.edu/psychiatry',
  'October 15, 2024',
  'March 15, 2025',
  1968,
  'ACGME',
  4,
  63000,
  65000,
  67000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,200)', 'Vacation (4 weeks)', 'Sick leave', 'Mental health support'],
  ARRAY['Inpatient Psychiatry', 'Outpatient Psychiatry', 'Emergency Psychiatry', 'Child Psychiatry', 'Addiction Medicine', 'Consultation-Liaison', 'Research', 'Electives'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Interest in mental health', 'Strong communication skills'],
  '{"applications": 1900, "interviews": 140, "match_rate": "89%", "board_pass_rate": "93%", "chief_residents": 4}'::jsonb,
  ARRAY['Child Psychiatry (4)', 'Addiction Medicine (3)', 'Forensic Psychiatry (2)', 'Consultation-Liaison (5)'],
  'psychiatry@stanford.edu',
  '(650) 723-4000',
  'Innovative psychiatry training with focus on research, technology, and comprehensive patient care.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Cardiology Fellowship
(
  'Cardiology Fellowship Program',
  'Cleveland Clinic',
  'Cardiology',
  'Fellowship',
  'Cleveland',
  'OH',
  12,
  'Dr. Amanda Foster, MD',
  'https://clevelandclinic.org/cardiology',
  'January 15, 2025',
  'June 15, 2025',
  1970,
  'ACGME',
  3,
  75000,
  77000,
  79000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($4,000)', 'Vacation (3 weeks)', 'Sick leave', 'Research support'],
  ARRAY['General Cardiology', 'Interventional Cardiology', 'Electrophysiology', 'Heart Failure', 'Cardiac Imaging', 'Preventive Cardiology', 'Research'],
  ARRAY['Completed Internal Medicine residency', 'Board eligible/certified in Internal Medicine', 'Strong cardiology interest', 'Research experience'],
  '{"applications": 800, "interviews": 60, "match_rate": "85%", "board_pass_rate": "98%", "chief_fellows": 2}'::jsonb,
  ARRAY['Interventional Cardiology (4)', 'Electrophysiology (2)', 'Heart Failure (3)', 'Cardiac Imaging (2)'],
  'cardiology@ccf.org',
  '(216) 444-2200',
  'World-class cardiology fellowship with cutting-edge technology and research opportunities.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Orthopedic Surgery
(
  'Orthopedic Surgery Residency Program',
  'Hospital for Special Surgery',
  'Orthopedic Surgery',
  'Residency',
  'New York',
  'NY',
  15,
  'Dr. James Wilson, MD',
  'https://hss.edu/orthopedic-surgery',
  'October 15, 2024',
  'March 15, 2025',
  1955,
  'ACGME',
  5,
  69000,
  71000,
  73000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($4,000)', 'Vacation (4 weeks)', 'Sick leave', 'Research stipend'],
  ARRAY['General Orthopedics', 'Trauma Surgery', 'Sports Medicine', 'Spine Surgery', 'Joint Replacement', 'Hand Surgery', 'Pediatric Orthopedics', 'Research'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Strong surgical interest', 'Research experience', 'Physical stamina'],
  '{"applications": 1200, "interviews": 75, "match_rate": "82%", "board_pass_rate": "94%", "chief_residents": 2}'::jsonb,
  ARRAY['Sports Medicine (3)', 'Spine Surgery (2)', 'Hand Surgery (2)', 'Joint Replacement (4)', 'Trauma Surgery (2)'],
  'orthopedics@hss.edu',
  '(212) 606-1000',
  'Premier orthopedic surgery training with focus on sports medicine and advanced surgical techniques.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Radiology Programs
(
  'Diagnostic Radiology Residency Program',
  'University of California San Francisco',
  'Radiology',
  'Residency',
  'San Francisco',
  'CA',
  20,
  'Dr. Patricia Brown, MD',
  'https://radiology.ucsf.edu',
  'October 15, 2024',
  'March 15, 2025',
  1962,
  'ACGME',
  4,
  64000,
  66000,
  68000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($3,000)', 'Vacation (4 weeks)', 'Technology stipend'],
  ARRAY['General Radiology', 'CT/MRI', 'Ultrasound', 'Nuclear Medicine', 'Interventional Radiology', 'Neuroradiology', 'Body Imaging', 'Research'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Strong analytical skills', 'Interest in technology'],
  '{"applications": 1600, "interviews": 100, "match_rate": "87%", "board_pass_rate": "96%", "chief_residents": 3}'::jsonb,
  ARRAY['Interventional Radiology (3)', 'Neuroradiology (4)', 'Body Imaging (5)', 'Nuclear Medicine (2)'],
  'radiology@ucsf.edu',
  '(415) 476-9000',
  'Advanced radiology training with state-of-the-art imaging technology and research focus.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Anesthesiology Programs
(
  'Anesthesiology Residency Program',
  'University of Michigan Medical Center',
  'Anesthesiology',
  'Residency',
  'Ann Arbor',
  'MI',
  32,
  'Dr. Kevin Davis, MD',
  'https://medicine.umich.edu/anesthesiology',
  'October 15, 2024',
  'March 15, 2025',
  1967,
  'ACGME',
  4,
  65000,
  67000,
  69000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,500)', 'Vacation (4 weeks)', 'Sick leave'],
  ARRAY['General Anesthesia', 'Regional Anesthesia', 'Cardiac Anesthesia', 'Pediatric Anesthesia', 'Obstetric Anesthesia', 'Pain Medicine', 'Critical Care', 'Research'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Strong science background', 'Attention to detail'],
  '{"applications": 1400, "interviews": 110, "match_rate": "86%", "board_pass_rate": "95%", "chief_residents": 4}'::jsonb,
  ARRAY['Pain Medicine (5)', 'Cardiac Anesthesia (3)', 'Pediatric Anesthesia (2)', 'Critical Care (4)'],
  'anesthesiology@umich.edu',
  '(734) 936-4280',
  'Comprehensive anesthesiology training with subspecialty tracks and research opportunities.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Neurology Programs
(
  'Neurology Residency Program',
  'Yale School of Medicine',
  'Neurology',
  'Residency',
  'New Haven',
  'CT',
  16,
  'Dr. Susan Garcia, MD',
  'https://medicine.yale.edu/neurology',
  'October 15, 2024',
  'March 15, 2025',
  1964,
  'ACGME',
  4,
  66000,
  68000,
  70000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($3,200)', 'Vacation (4 weeks)', 'Research support'],
  ARRAY['General Neurology', 'Stroke Neurology', 'Epilepsy', 'Movement Disorders', 'Neuromuscular', 'Neuroimaging', 'Neurointensive Care', 'Research'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Strong neuroscience background', 'Research experience preferred'],
  '{"applications": 1100, "interviews": 80, "match_rate": "84%", "board_pass_rate": "97%", "chief_residents": 2}'::jsonb,
  ARRAY['Stroke Neurology (2)', 'Epilepsy (3)', 'Movement Disorders (2)', 'Neuromuscular (1)', 'Neurointensive Care (2)'],
  'neurology@yale.edu',
  '(203) 785-4085',
  'Excellence in neurological training with emphasis on research and subspecialty care.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Dermatology Programs
(
  'Dermatology Residency Program',
  'University of Pennsylvania',
  'Dermatology',
  'Residency',
  'Philadelphia',
  'PA',
  8,
  'Dr. Maria Rodriguez, MD',
  'https://pennmedicine.org/dermatology',
  'October 15, 2024',
  'March 15, 2025',
  1969,
  'ACGME',
  4,
  68000,
  70000,
  72000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($3,500)', 'Vacation (4 weeks)', 'Research stipend'],
  ARRAY['General Dermatology', 'Dermatopathology', 'Pediatric Dermatology', 'Dermatologic Surgery', 'Cosmetic Dermatology', 'Research', 'Electives'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Excellent academic record', 'Research experience required', 'Strong USMLE scores'],
  '{"applications": 1800, "interviews": 40, "match_rate": "75%", "board_pass_rate": "99%", "chief_residents": 1}'::jsonb,
  ARRAY['Dermatopathology (2)', 'Pediatric Dermatology (1)', 'Dermatologic Surgery (2)', 'Academic Dermatology (3)'],
  'dermatology@pennmedicine.upenn.edu',
  '(215) 662-4000',
  'Highly competitive dermatology program with excellence in clinical care and research.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Pathology Programs
(
  'Anatomic and Clinical Pathology Residency Program',
  'Washington University School of Medicine',
  'Pathology',
  'Residency',
  'St. Louis',
  'MO',
  14,
  'Dr. Thomas Anderson, MD',
  'https://pathology.wustl.edu',
  'October 15, 2024',
  'March 15, 2025',
  1961,
  'ACGME',
  4,
  62000,
  64000,
  66000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,800)', 'Vacation (4 weeks)', 'Research support'],
  ARRAY['Anatomic Pathology', 'Clinical Pathology', 'Surgical Pathology', 'Cytopathology', 'Forensic Pathology', 'Molecular Pathology', 'Research'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Strong analytical skills', 'Research interest'],
  '{"applications": 900, "interviews": 70, "match_rate": "91%", "board_pass_rate": "97%", "chief_residents": 2}'::jsonb,
  ARRAY['Surgical Pathology (3)', 'Cytopathology (2)', 'Forensic Pathology (1)', 'Molecular Pathology (2)'],
  'pathology@wustl.edu',
  '(314) 362-5000',
  'Comprehensive pathology training with strong research component and subspecialty opportunities.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Obstetrics and Gynecology
(
  'Obstetrics and Gynecology Residency Program',
  'Brigham and Women''s Hospital',
  'Obstetrics and Gynecology',
  'Residency',
  'Boston',
  'MA',
  20,
  'Dr. Rachel Kim, MD',
  'https://brighamandwomens.org/obgyn',
  'October 15, 2024',
  'March 15, 2025',
  1966,
  'ACGME',
  4,
  65000,
  67000,
  69000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,700)', 'Vacation (4 weeks)', 'Parental leave'],
  ARRAY['General Obstetrics', 'General Gynecology', 'Maternal-Fetal Medicine', 'Gynecologic Oncology', 'Reproductive Endocrinology', 'Urogynecology', 'Family Planning'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Interest in women''s health', 'Strong surgical skills'],
  '{"applications": 1600, "interviews": 100, "match_rate": "88%", "board_pass_rate": "96%", "chief_residents": 3}'::jsonb,
  ARRAY['Maternal-Fetal Medicine (3)', 'Gynecologic Oncology (2)', 'Reproductive Endocrinology (2)', 'Urogynecology (1)'],
  'obgyn@bwh.harvard.edu',
  '(617) 732-5500',
  'Excellence in women''s health with comprehensive training and research opportunities.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Community Hospital Programs
(
  'Family Medicine Residency Program',
  'Riverside Community Hospital',
  'Family Medicine',
  'Residency',
  'Riverside',
  'CA',
  18,
  'Dr. Carlos Mendez, MD',
  'https://riversidecommunity.org/family-medicine',
  'October 15, 2024',
  'March 15, 2025',
  1985,
  'ACGME',
  3,
  56000,
  58000,
  60000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($1,800)', 'Vacation (4 weeks)'],
  ARRAY['Family Medicine Clinic', 'Internal Medicine', 'Pediatrics', 'Obstetrics', 'Emergency Medicine', 'Community Health', 'Rural Medicine'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Interest in primary care', 'Community service'],
  '{"applications": 800, "interviews": 80, "match_rate": "92%", "board_pass_rate": "91%", "chief_residents": 2}'::jsonb,
  ARRAY['Family Medicine Faculty (12)', 'Sports Medicine (1)', 'Geriatrics (1)'],
  'familymedicine@rch.org',
  '(951) 788-3000',
  'Community-focused family medicine training with emphasis on underserved populations.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Additional Programs for diversity
(
  'Emergency Medicine Residency Program',
  'Denver Health Medical Center',
  'Emergency Medicine',
  'Residency',
  'Denver',
  'CO',
  24,
  'Dr. Mark Thompson, MD',
  'https://denverhealth.org/emergency-medicine',
  'October 15, 2024',
  'March 15, 2025',
  1978,
  'ACGME',
  4,
  61000,
  63000,
  65000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,200)', 'Vacation (4 weeks)'],
  ARRAY['Emergency Department', 'Trauma', 'Critical Care', 'Toxicology', 'EMS', 'Wilderness Medicine', 'Research'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Emergency medicine interest', 'High-stress tolerance'],
  '{"applications": 1800, "interviews": 120, "match_rate": "89%", "board_pass_rate": "94%", "chief_residents": 3}'::jsonb,
  ARRAY['Emergency Medicine Faculty (18)', 'Critical Care (2)', 'Toxicology (1)', 'EMS (3)'],
  'emergency@denverhealth.org',
  '(303) 436-6000',
  'Urban emergency medicine training with high-volume trauma and diverse patient population.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

(
  'Pediatric Surgery Fellowship Program',
  'Children''s Hospital of Philadelphia',
  'Pediatric Surgery',
  'Fellowship',
  'Philadelphia',
  'PA',
  4,
  'Dr. Nancy White, MD',
  'https://chop.edu/pediatric-surgery',
  'January 15, 2025',
  'June 15, 2025',
  1972,
  'ACGME',
  2,
  78000,
  80000,
  0,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($4,500)', 'Vacation (3 weeks)', 'Research support'],
  ARRAY['General Pediatric Surgery', 'Neonatal Surgery', 'Pediatric Trauma', 'Minimally Invasive Surgery', 'Pediatric Urology', 'Research'],
  ARRAY['Completed General Surgery residency', 'Board eligible/certified in Surgery', 'Pediatric surgery interest', 'Research experience'],
  '{"applications": 200, "interviews": 25, "match_rate": "70%", "board_pass_rate": "100%", "chief_fellows": 1}'::jsonb,
  ARRAY['Pediatric Surgery Faculty (4)'],
  'pediatricsurgery@chop.edu',
  '(215) 590-1000',
  'Premier pediatric surgery fellowship with comprehensive training in all aspects of pediatric surgical care.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Physical Medicine & Rehabilitation
(
  'Physical Medicine and Rehabilitation Residency Program',
  'Rehabilitation Institute of Chicago',
  'Physical Medicine and Rehabilitation',
  'Residency',
  'Chicago',
  'IL',
  12,
  'Dr. Lisa Chang, MD',
  'https://ric.org/pmr',
  'October 15, 2024',
  'March 15, 2025',
  1980,
  'ACGME',
  4,
  63000,
  65000,
  67000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($2,400)', 'Vacation (4 weeks)'],
  ARRAY['General PM&R', 'Spinal Cord Injury', 'Brain Injury', 'Stroke Rehabilitation', 'Sports Medicine', 'Pain Medicine', 'Pediatric Rehabilitation'],
  ARRAY['MD or DO degree', 'USMLE Step 1 and 2 CK', 'Interest in rehabilitation', 'Patient-centered approach'],
  '{"applications": 600, "interviews": 60, "match_rate": "90%", "board_pass_rate": "95%", "chief_residents": 2}'::jsonb,
  ARRAY['Spinal Cord Injury Medicine (2)', 'Brain Injury Medicine (1)', 'Sports Medicine (2)', 'Pain Medicine (3)'],
  'pmr@ric.org',
  '(312) 238-1000',
  'Leading rehabilitation medicine training with focus on comprehensive patient care and recovery.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Gastroenterology Fellowship
(
  'Gastroenterology Fellowship Program',
  'University of Chicago Medical Center',
  'Gastroenterology',
  'Fellowship',
  'Chicago',
  'IL',
  8,
  'Dr. Andrew Park, MD',
  'https://uchicagomedicine.org/gastroenterology',
  'January 15, 2025',
  'June 15, 2025',
  1973,
  'ACGME',
  3,
  76000,
  78000,
  80000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($4,200)', 'Vacation (3 weeks)', 'Research support'],
  ARRAY['General Gastroenterology', 'Hepatology', 'Inflammatory Bowel Disease', 'Advanced Endoscopy', 'Interventional Endoscopy', 'Research'],
  ARRAY['Completed Internal Medicine residency', 'Board eligible/certified in Internal Medicine', 'Strong GI interest', 'Research experience'],
  '{"applications": 700, "interviews": 50, "match_rate": "82%", "board_pass_rate": "98%", "chief_fellows": 1}'::jsonb,
  ARRAY['Advanced Endoscopy (2)', 'Hepatology (3)', 'IBD (2)', 'Academic Gastroenterology (5)'],
  'gastroenterology@uchicago.edu',
  '(773) 702-1000',
  'Advanced gastroenterology training with cutting-edge endoscopic techniques and research.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Pulmonology Fellowship
(
  'Pulmonary and Critical Care Medicine Fellowship Program',
  'University of Washington Medical Center',
  'Pulmonology',
  'Fellowship',
  'Seattle',
  'WA',
  10,
  'Dr. Jennifer Liu, MD',
  'https://medicine.uw.edu/pulmonary',
  'January 15, 2025',
  'June 15, 2025',
  1971,
  'ACGME',
  3,
  74000,
  76000,
  78000,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($3,800)', 'Vacation (3 weeks)', 'Research support'],
  ARRAY['General Pulmonology', 'Critical Care Medicine', 'Interventional Pulmonology', 'Sleep Medicine', 'Lung Transplant', 'Research'],
  ARRAY['Completed Internal Medicine residency', 'Board eligible/certified in Internal Medicine', 'ICU experience', 'Research interest'],
  '{"applications": 650, "interviews": 45, "match_rate": "80%", "board_pass_rate": "97%", "chief_fellows": 1}'::jsonb,
  ARRAY['Critical Care Medicine (4)', 'Interventional Pulmonology (2)', 'Sleep Medicine (2)', 'Academic Pulmonology (6)'],
  'pulmonary@uw.edu',
  '(206) 598-4615',
  'Comprehensive pulmonary and critical care training with research excellence.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Infectious Disease Fellowship
(
  'Infectious Diseases Fellowship Program',
  'Emory University School of Medicine',
  'Infectious Diseases',
  'Fellowship',
  'Atlanta',
  'GA',
  6,
  'Dr. Robert Taylor, MD',
  'https://medicine.emory.edu/infectious-diseases',
  'January 15, 2025',
  'June 15, 2025',
  1974,
  'ACGME',
  2,
  73000,
  75000,
  0,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($3,600)', 'Vacation (3 weeks)', 'Research support'],
  ARRAY['General Infectious Diseases', 'HIV Medicine', 'Transplant Infectious Diseases', 'Antimicrobial Stewardship', 'Infection Control', 'Research'],
  ARRAY['Completed Internal Medicine residency', 'Board eligible/certified in Internal Medicine', 'Microbiology knowledge', 'Research experience'],
  '{"applications": 400, "interviews": 35, "match_rate": "78%", "board_pass_rate": "99%", "chief_fellows": 1}'::jsonb,
  ARRAY['HIV Medicine (2)', 'Transplant ID (1)', 'Academic Infectious Diseases (3)'],
  'infectious.diseases@emory.edu',
  '(404) 712-2000',
  'Leading infectious diseases training with focus on HIV, transplant, and antimicrobial stewardship.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
),

-- Endocrinology Fellowship
(
  'Endocrinology Fellowship Program',
  'University of California Los Angeles',
  'Endocrinology',
  'Fellowship',
  'Los Angeles',
  'CA',
  8,
  'Dr. Michelle Wong, MD',
  'https://medicine.ucla.edu/endocrinology',
  'January 15, 2025',
  'June 15, 2025',
  1976,
  'ACGME',
  2,
  74000,
  76000,
  0,
  ARRAY['Health insurance', 'Dental insurance', 'Vision insurance', 'Malpractice insurance', 'Educational allowance ($3,700)', 'Vacation (3 weeks)', 'Research support'],
  ARRAY['General Endocrinology', 'Diabetes Management', 'Thyroid Disorders', 'Reproductive Endocrinology', 'Bone and Mineral Disorders', 'Research'],
  ARRAY['Completed Internal Medicine residency', 'Board eligible/certified in Internal Medicine', 'Endocrinology interest', 'Research experience'],
  '{"applications": 500, "interviews": 40, "match_rate": "76%", "board_pass_rate": "98%", "chief_fellows": 1}'::jsonb,
  ARRAY['Academic Endocrinology (6)', 'Diabetes Specialist (2)'],
  'endocrinology@ucla.edu',
  '(310) 825-7922',
  'Comprehensive endocrinology training with emphasis on diabetes, thyroid, and metabolic disorders.',
  'gme_business_review_2024.xlsx',
  (SELECT id FROM users WHERE role = 'administrator' LIMIT 1),
  NOW()
);